# Generated by Django 5.0.6 on 2024-06-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin_url', '0002_profile_rename_url_url_url_experience_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
