# Generated by Django 5.0.6 on 2024-06-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin_url', '0005_alter_education_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
